# =============================================================================== #
# LazyGit:                                                                        #
# =============================================================================== #
gui:
  scrollHeight: 2
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "left"
  language: "en"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8ccf7e"
      - bold
    inactiveBorderColor:
      - "#6cbfbf"
    searchingActiveBorderColor:
      - "#c4b28a"
      - bold
    optionsTextColor:
      - "#67b0e8"
    selectedLineBgColor:
      - "#232a2d"
    selectedRangeBgColor:
      - "#8ccf7e"
    cherryPickedCommitBgColor:
      - "#e5c76b"
    cherryPickedCommitFgColor:
      - "#8ccf7e"
    unstagedChangesColor:
      - "#e57474"
    defaultFgColor:
      - default
  commitLength:
    show: true

git:
  paging:
    colorArg: "always"
    pager: "delta --dark --paging=never"
  commit:
    signoff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
