# ----------------------------------------------------------- #
# --  Git For Lazy Peaple like me:                            #
# ----------------------------------------------------------- #
gui:
  scrollHeight: 2
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "left"
  language: "en"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - yellow
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - "#363537"
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - yellow
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  commitLength:
    show: true

git:
  paging:
    colorArg: "always"
    pager: "delta --dark --paging=never"
  commit:
    signoff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
