# =============================================================================== #
# LazyGit:                                                                        #
# =============================================================================== #
gui:
  scrollHeight: 2
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "left"
  language: "en"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8C977D"
      - bold
    inactiveBorderColor:
      - "#BBB6B6"
    searchingActiveBorderColor:
      - "#c4b28a"
      - bold
    optionsTextColor:
      - "#8DA3B9"
    selectedLineBgColor:
      - "#1F1F1F"
    selectedRangeBgColor:
      - "#8AA6A2"
    cherryPickedCommitBgColor:
      - "#e5c76b"
    cherryPickedCommitFgColor:
      - "#8AA6A2"
    unstagedChangesColor:
      - "#B66467"
    defaultFgColor:
      - default
  commitLength:
    show: true

git:
  paging:
    colorArg: "always"
    pager: "delta --dark --paging=never"
  commit:
    signoff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
