# =============================================================================== #
# Yazi Cli  File Manager Keymaps :                                                #
# =============================================================================== #
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	# General
	{ on = "A", run = "create --dir" },
  { on = "e", run = ["open", "quit"], desc = "edit" },
	# Hopping
	{ on = "k", run = "arrow prev" },
	{ on = "j", run = "arrow next" },
	{ on = "<C-u>", run = "arrow -5" },
	{ on = "<C-d>", run = "arrow 5" },
	# Navigation
	{ on = "h", run = "leave" },
	{ on = "l", run = "plugin smart-enter" },
	{ on = "<C-h>", run = "leave" },
	{ on = "<Tab>", run = "plugin smart-enter" },
	# Find
	{ on = "-", run = "find_arrow" },
	{ on = "=", run = "find_arrow --previous" },
	# Shell
	{ on = "$", run = 'shell --block $SHELL' },
	{ on = ["!"], run = 'shell nu --block --confirm' },
	# Jump
  { on   = "f", run  = "plugin jump-to-char", desc = "Jump to char" },
	# BookMarks
  { on   = [ "~" ], run  = 'cd "~"', desc = "Go To Downloads" },
  { on   = [ "b", "h" ], run  = 'cd "~"', desc = "Go To Downloads" },
  { on   = [ "b", "d" ], run  = 'cd "~/Downloads"', desc = "Go To Downloads" },
  { on   = [ "b", "v" ], run  = 'cd "~/Videos/programming"', desc = "Go To Videos Programming" },
  { on   = [ "b", "m" ], run  = 'cd "~/Music"', desc = "Go To Videos Programming" },
  { on   = [ "b", "i" ], run  = 'cd "~/Pictures/pix"', desc = "Go To Pictures" },
  { on   = [ "b", "p" ], run  = 'cd "~/Projects"', desc = "Go To Projects" },
  { on   = [ "b", "w" ], run  = 'cd "~/.local/wayland-void"', desc = "Go To Projects" }
]

[tasks]
prepend_keymap = [
	{ on = "k", run = "arrow -1" },
	{ on = "j", run = "arrow 1" },
]

[spot]
prepend_keymap = [
	{ on = "k", run = "arrow -1" },
	{ on = "j", run = "arrow 1" },
	{ on = "n", run = "swipe -1" },
	{ on = "i", run = "swipe 1" },
]

[pick]
prepend_keymap = [
	{ on = "k", run = "arrow -1" },
	{ on = "j", run = "arrow 1" },
]

[input]
prepend_keymap = [
	# Mode
	{ on = "i",     run = "insert" },
	{ on = "<C-n>", run = [ "move bol", "insert" ] },
	{ on = "<C-i>", run = [ "move eol", "insert --append" ] },
	# Character-wise movement
	{ on = "n", run = "move -1" },
	{ on = "i", run = "move 1" },
	# Character Delete
	{ on = "x", run = [ "delete", "move 1 --in-operating" ] },
	# Undo/Redo
	{ on = "u", run = "undo" },
	{ on = "U", run = "redo" },
]

[confirm]
prepend_keymap = [
	{ on = "j", run = "arrow -1" },
	{ on = "k", run = "arrow 1" },
]

[cmp]
prepend_keymap = [
	{ on = "<C-k>", run = "arrow -1" },
	{ on = "<C-j>", run = "arrow 1" },
]

[help]
prepend_keymap = [
	# Navigation
	{ on = "j", run = "arrow -1" },
	{ on = "k", run = "arrow 1" },
	{ on = "<C-u>", run = "arrow -5" },
	{ on = "<C-d>", run = "arrow 5" },
]

[completion]
prepend_keymap = [
	{ on = [ "<C-j>" ], run = [ "arrow 1", "insert" ] },
	{ on = [ "<C-k>" ], run = [ "arrow -1", "insert --append" ] },
]
