[manager]
prepend_keymap = [
	{ on = [ "e" ], run = "open"},
	{ on = [ "A" ], run = "create --dir"},
	# { on   = "<Esc>", run  = "close", desc = "Cancel input" },
	{ on = "!", run  = 'shell "powershell.exe" --block', desc = "Open PowerShell here" },
	{ on = "l",		run  = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "f", run  = "plugin jump-to-char", desc = "Jump to char" }
]
[completion]
prepend_keymap = [
	{ on = [ "<C-j>" ], run = [ "arrow 1", "insert" ] },
	{ on = [ "<C-k>" ], run = [ "arrow -1", "insert --append" ] },
]
