# =============================================================================== #
# Yazi Cli File Manager Theme:                                                    #
# =============================================================================== #
[mgr]
cwd = { fg = "#e57474" }
hovered         = { reversed = true }
preview_hovered = { underline = true }
find_keyword  = { fg = "#8ccf7e", bold = true, italic = true, underline = true }
find_position = { fg = "#c47fd5", bg = "reset", bold = true, italic = true }
marker_copied   = { fg = "#8ccf7e",  bg = "#8ccf7e" }
marker_cut      = { fg = "#e57474",    bg = "#e57474" }
marker_marked   = { fg = "#e57474",   bg = "#e57474" }
marker_selected = { fg = "#8ccf7e", bg = "#8ccf7e" }
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1
count_copied   = { fg = "#232a2d", bg = "#8ccf7e" }
count_cut      = { fg = "#232a2d", bg = "#e57474" }
count_selected = { fg = "#232a2d", bg = "#8ccf7e" }
border_symbol = "│"
border_style  = { fg = "#232a2d" }
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#232a2d", bg = "#232a2d" }
mode_normal = { bg = "#e57474", bold = true }
mode_select = { bg = "#e57474", bold = true }
mode_unset  = { bg = "#e57474", bold = true }
progress_label  = { bold = true }
progress_normal = { fg = "#e57474", bg = "#232a2d" }
progress_error  = { fg = "#e57474", bg = "#232a2d" }
permissions_t = { fg = "#8ccf7e" }
permissions_r = { fg = "#8ccf7e" }
permissions_w = { fg = "#e57474" }
permissions_x = { fg = "#e57474" }
permissions_s = { fg = "#2d353b" }

[select]
border   = { fg = "#e57474" }
active   = { fg = "#c47fd5", bold = true }
inactive = {}

[input]
border   = { fg = "#e57474" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#e57474" }
active   = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#e57474" }
title   = {}
hovered = { fg = "#c47fd5", underline = true }

[which]
cols            = 3
mask            = { bg = "#232a2d" }
cand            = { fg = "#e57474" }
rest            = { fg = "#2d353b" }
desc            = { fg = "#c47fd5" }
separator       = "  "
separator_style = { fg = "#2d353b" }

[help]
on      = { fg = "#e57474" }
run     = { fg = "#c47fd5" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#232a2d", bg = "#d3c6aa" }

[notify]
title_info  = { fg = "#8ccf7e" }
title_warn  = { fg = "#8ccf7e" }
title_error = { fg = "#e57474" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]
rules = [
	{ mime = "image/*", fg = "#e57474" },
	{ mime = "{audio,video}/*", fg = "#8ccf7e" },
	{ mime = "application/*zip", fg = "#e57474" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e57474" },
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#e57474" },
	{ name = "*", fg = "#8ccf7e" },
	{ name = "*/", fg = "#8ccf7e" }
]
