# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#a6a69c" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#c4b28a", bold = true, italic = true, underline = true }
find_position = { fg = "#a292a3", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#8a9a7b",  bg = "#8a9a7b" }
marker_cut      = { fg = "#c4746e",    bg = "#c4746e" }
marker_marked   = { fg = "#a6a69c",   bg = "#a6a69c" }
marker_selected = { fg = "#c4b28a", bg = "#c4b28a" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#343f44", bg = "#8a9a7b" }
count_cut      = { fg = "#343f44", bg = "#c4746e" }
count_selected = { fg = "#343f44", bg = "#c4b28a" }

# Border
border_symbol = "│"
border_style  = { fg = "#4f585e" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#343f44", bg = "#343f44" }

# Mode
mode_normal = { bg = "#a6a69c", bold = true }
mode_select = { bg = "#c4746e", bold = true }
mode_unset  = { bg = "#c4746e", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#a6a69c", bg = "#232a2e" }
progress_error  = { fg = "#c4746e", bg = "#232a2e" }

# Permissions
permissions_t = { fg = "#8a9a7b" }
permissions_r = { fg = "#c4b28a" }
permissions_w = { fg = "#c4746e" }
permissions_x = { fg = "#a6a69c" }
permissions_s = { fg = "#2d353b" }

# : }}}


# : Select {{{

[select]
border   = { fg = "#a6a69c" }
active   = { fg = "#a292a3", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#a6a69c" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "#a6a69c" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#a6a69c" }
title   = {}
hovered = { fg = "#a292a3", underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#232a2e" }
cand            = { fg = "#a6a69c" }
rest            = { fg = "#2d353b" }
desc            = { fg = "#a292a3" }
separator       = "  "
separator_style = { fg = "#2d353b" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#a6a69c" }
run     = { fg = "#a292a3" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#232a2e", bg = "#d3c6aa" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#8a9a7b" }
title_warn  = { fg = "#c4b28a" }
title_error = { fg = "#c4746e" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#a6a69c" },

	# Media
	{ mime = "{audio,video}/*", fg = "#a292a3" },

	# Archives
	{ mime = "application/*zip", fg = "#c4746e" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c4746e" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a6a69c" },

	# Fallback
	{ name = "*", fg = "#83c092" },
	{ name = "*/", fg = "#8a9a7b" }
]

# : }}}
