# =============================================================================== #
# Yazi Cli File Manager Theme:                                                    #
# =============================================================================== #
[manager]
cwd = { fg = "#B66467" }
hovered         = { reversed = true }
preview_hovered = { underline = true }
find_keyword  = { fg = "#c4b28a", bold = true, italic = true, underline = true }
find_position = { fg = "#A988B0", bg = "reset", bold = true, italic = true }
marker_copied   = { fg = "#8C977D",  bg = "#8C977D" }
marker_cut      = { fg = "#B66467",    bg = "#B66467" }
marker_marked   = { fg = "#B66467",   bg = "#B66467" }
marker_selected = { fg = "#c4b28a", bg = "#c4b28a" }
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1
count_copied   = { fg = "#424242", bg = "#8C977D" }
count_cut      = { fg = "#424242", bg = "#B66467" }
count_selected = { fg = "#424242", bg = "#c4b28a" }
border_symbol = "│"
border_style  = { fg = "#4f585e" }
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#424242", bg = "#424242" }
mode_normal = { bg = "#B66467", bold = true }
mode_select = { bg = "#B66467", bold = true }
mode_unset  = { bg = "#B66467", bold = true }
progress_label  = { bold = true }
progress_normal = { fg = "#B66467", bg = "#1F1F1F" }
progress_error  = { fg = "#B66467", bg = "#1F1F1F" }
permissions_t = { fg = "#8C977D" }
permissions_r = { fg = "#c4b28a" }
permissions_w = { fg = "#B66467" }
permissions_x = { fg = "#B66467" }
permissions_s = { fg = "#2d353b" }

[select]
border   = { fg = "#B66467" }
active   = { fg = "#A988B0", bold = true }
inactive = {}

[input]
border   = { fg = "#B66467" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#B66467" }
active   = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#B66467" }
title   = {}
hovered = { fg = "#A988B0", underline = true }

[which]
cols            = 3
mask            = { bg = "#1F1F1F" }
cand            = { fg = "#B66467" }
rest            = { fg = "#2d353b" }
desc            = { fg = "#A988B0" }
separator       = "  "
separator_style = { fg = "#2d353b" }

[help]
on      = { fg = "#B66467" }
run     = { fg = "#A988B0" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#1F1F1F", bg = "#d3c6aa" }

[notify]
title_info  = { fg = "#8C977D" }
title_warn  = { fg = "#c4b28a" }
title_error = { fg = "#B66467" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]
rules = [
	{ mime = "image/*", fg = "#B66467" },
	{ mime = "{audio,video}/*", fg = "#8C977D" },
	{ mime = "application/*zip", fg = "#B66467" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#B66467" },
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#B66467" },
	{ name = "*", fg = "#83c092" },
	{ name = "*/", fg = "#8C977D" }
]
