# =============================================================================== #
# Neovide => Neovim Gui With Smooth Animation:                                    #
# =============================================================================== #
frame = "none"
maximized = false
title-hidden = true
idle = true
tabs = true
theme = "auto"
[font]
size = 9
hinting = "full"
edging = "antialias"
[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "W400"
